### PR TITLE
select amd64 machines for this deployment

### PR DESCRIPTION
**Pull request by golatoye**
when running arm64 machines in the cluster select the amd64 machines

### CODE REVIEW

**Comment by salaboy** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **salaboy**

If they are not already assigned, you can assign the PR to them by writing `/assign @salaboy` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-operate-helm).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zeebe-io/zeebe-operate-helm/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by salaboy** [comment]
Hi @golatoye. Thanks for your PR.

I'm waiting for a [zeebe-io](https://github.com/orgs/zeebe-io/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/zeebe-io/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=zeebe-io%2Fzeebe-operate-helm).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by salaboy** [comment]
@golatoye Hi, thanks a lot for your contribution, but I cannot merge this as it is, you need to make it configurable via the values file in order to be parameterizable. If I push the change as it is, it will require all deployments to have amd64 nodes to schedule the brokers. I am happy to accept the change if you make it a configuration value, such as:
- Using a variable instead of a hardcoding value such as "amd64": https://github.com/zeebe-io/zeebe-operate-helm/blob/master/zeebe-operate/templates/deployment.yaml#L19
- Values.yaml file provides the value that you want to use, so it can be overridden: https://github.com/zeebe-io/zeebe-operate-helm/blob/master/zeebe-operate/values.yaml#L12 
 I hope that makes sense.

**Review by salaboy — CHANGES_REQUESTED** [review]
Check my comment in the PR

**Comment by golatoye** [comment]
@salaboy 

Thanks for reviewing 

Will make the changes . I have a few question for you if you can clarify 
I thought the camunda/operate docker images only work on amd64 now any way.
from the docker hub link https://hub.docker.com/r/camunda/operate/tags 
is that not the case ? 

how do you want me to make the use a template parameter and default it to amd64 ?

**Comment by salaboy** [comment]
@golatoye you are in some way right.. but we haven't faced any issue so far to let kubernetes choose the right node. 


Here in docker docs it is explained that we can provide a multi architecture support for our images: 
https://docs.docker.com/docker-for-mac/multi-arch/

Maybe we should open an issue for that. @menski what do you think? have you come across such requirements? 

I would like to have a parameter for `nodeSelectors` in general and the default should be nothing defined.

**Comment by golatoye** [comment]
@salaboy ok will make the change. I have a cluster where I connect a raspberry pi and I get pods scheduled on it and it does not work. I remember seeing the  ngix ingress controller had this problem.

**Comment by golatoye** [comment]
also @salaboy you sure you want `nodeSelectors `as not `nodeSelector`

**Comment by golatoye** [comment]
@salaboy ok made changes to request to as suggested . I used `nodeSelector` rather than `nodeSelectors` to be consistent with the kubernetes resource schema. if you would still like me to use `nodeSelectors` let me know and I will update

**Comment by golatoye** [comment]
@salaboy just checking if you need anything else here ?

**Comment by salaboy** [comment]
@golatoye sorry for my delay in response, and thanks for the ping in slack, as I mention there, the name that you are using is fine, but the changes in the values.yaml file is not needed. If you can fix that I am happy to merge.

**Comment by salaboy** [comment]
@golatoye also, it will be great if you add the `nodeSelector` field into the Readme file as well.. so people knows that they can configure that if needed.

**Review by salaboy — CHANGES_REQUESTED** [review]
Please add `nodeSelector` in readme file.

**Review by salaboy — CHANGES_REQUESTED** [review]
@golatoye please remove the 
 ```nodeSelector:``` from the `values.yaml` file, it is not needed if it is empty.

**Comment by salaboy** [comment]
@golatoye can you please rebase this PR? sorry that this went stale.

**Comment by ChrisKujawa** [comment]
This PR seems to be outdated. Sorry for the inconvenience. If you still interested in the changes feel free to reopen a new PR which is rebased to the latest state. It might make sense to create an issue first to discuss what the expected changes are.

**Pull request closed without merging**
